import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'South Indian',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Vegetarian',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'Quick and Easy',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'Punjabi',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'North Indian',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'Non Vegetarian',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    title: 'Mughlai',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    title: 'Kashmiri',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c9',
    title: 'Seafoods',
    color: Colors.pink,
  ),
  Category(
    id: 'c10',
    title: 'Desserts',
    color: Colors.teal,
  ),
];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c4',
    ],
    title: 'Chettinad Chicken Curry',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://i2.wp.com/swatisani.net/kitchen/wp-content/uploads/2015/10/IMG_9350.jpg',
    duration: 35,
    ingredients: [
      '1 tablespoon poppy seeds',
      '1 teaspoon coriander seeds',
      '1 teaspoon cumin seeds',
      '1 teaspoon anise seed/fennel seeds',
      '3 red chilies (dry)',
      '1 stick cinnamon (1 inch)',
      '2 cardamom pods',
      '3 cloves',
      '1/2 cup coconut (grated)',
      '2 teaspoons ginger paste',
      '2 teaspoons garlic paste',
      '2 to 3 tablespoons vegetable oil (or sunflower, canola, or ghee)',
      '10 to 15 curry leaves',
      '2 large onions (sliced fine)',
      '1 star anise',
      '2 tomatoes (chopped fine)',
      '1 teaspoon chili powder',
      '1-kilogram chicken (a whole chicken cut into bits or leg or breast pieces)',
      'Salt (to taste)',
      '2 teaspoons lime juice',
      'Garnish: chopped coriander leaves',
    ],
    steps: [
      'Heat a heavy pan or skillet on a medium flame and roast the poppy, coriander, cumin and fennel seeds, dry red chilies, cinnamon, cardamom, cloves, and coconut for 3 to 4 minutes. Remove from flame and allow to cool. Grind the mixture into a coarse powder in a clean, dry coffee grinder.',
      'Mix the ginger and garlic pastes with this powder and keep aside.',
      'In another deep pan, heat the oil and add the curry leaves. When they stop spluttering, add the sliced onions and fry till they are light brown.',
      'Add the spice paste and star anise and fry for another 2 to 3 minutes.',
      'Add the tomatoes and chili powder and stir well to mix all the ingredients.',
      'Add the chicken, cover and simmer till it is tender.',
      'When the chicken is done add lime juice, mix well and turn off the flame.',
      'Garnish with coriander leaves and serve.',
    ],
    isVegetarian: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c4',
    ],
    title: 'Roasted Butternut Squash Soup',
    affordability: Affordability.Pricey,
    complexity: Complexity.Hard,
    imageUrl:
        'https://www.thespruceeats.com/thmb/bL01aQGIjGrugE42ZKVWMGol04Q=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-478328269-5c82e4684cedfd000190b177.jpg',
    duration: 90,
    ingredients: [
      '1 large butternut squash (2 1/2 to 3 pounds)',
      '1 1/2 cups apple cider',
      '1/3 cup brown sugar',
      ' 2 cinnamon sticks (cut in half crosswise)',
      '2 tablespoons melted butter',
      '1 cup diced onion',
      '2 tablespoons butter',
      '4 cups chicken broth',
      'Dash ground ginger',
      'Dash ground nutmeg',
      '1/2 cup heavy cream',
      'Dash salt (or to taste)',
      'Optional: butter toasted pumpkin seeds (recipe below)',
    ],
    steps: [
      'Gather the ingredients.',
      'Using a vegetable peeler, peel the squash.',
      'Cut into chunks, removing seeds and soft fibers with a spoon.',
      'Put in a bowl; add apple cider, brown sugar, and cinnamon stick pieces then drizzle all over with the melted butter.',
      'Pour the mixture into a 9x13-inch baking pan; cover tightly with foil and cook at 450 F for 1 hour, or until very tender.',
      ' Meanwhile, cook diced onion in a large saucepan in the 2 tablespoons butter.',
      'When onion is very tender, add chicken broth. Bring to a boil. Remove from heat and set aside.',
      'When squash is very tender, remove from oven.',
      'Remove cinnamon from the squash.',
      'With a slotted spoon, transfer the squash to the chicken broth and onion mixture. Add about 1/4 cup of the roasting pan juices to the saucepan. Bring to a simmer.',
      'Working in about 4 batches, puree the squash mixture in a blender, then return to the saucepan.',
      'Stir in the ginger and nutmeg and the heavy cream, along with salt, to taste. Heat through.',
      'Serve with butter-toasted pumpkin seeds (below), if desired, or sprinkle with a little cinnamon, toasted pecans, or chopped peanuts.',
      'Butter-Toasted Pumpkin Seeds',
      'In a small skillet, heat 2 teaspoons butter.',
      'Add a few tablespoons of pumpkin seeds and cook over medium-low heat until lightly browned.',
      'Transfer to a paper towel to drain.',
      'Sprinkle with cinnamon sugar.',
    ],
    isVegetarian: true,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c10',
    ],
    title: 'Chocolate Pudding Cake',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.thespruceeats.com/thmb/O6BZRn2JNaF4ValdgsKtmOQ6SwQ=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/slices-of-chocolate-cake-with-powdered-sugar-on-plate-923818802-5ab11ca53418c60036db151e.jpg',
    duration: 50,
    ingredients: [
      '1 cup all-purpose flour',
      '3/4 cup granulated sugar',
      '1/4 cup plus 3 tablespoons unsweetened cocoa powder (divided)',
      '2 teaspoon baking powder',
      '1/4 teaspoon salt',
      '1/2 cup milk',
      '2 tablespoons vegetable oil (neutral flavor, such as canola or corn oil)',
      ' 1 teaspoon vanilla extract',
      '3/4 cup brown sugar (packed)',
      '1 3/4 cups boiling water',
    ],
    steps: [
      'Heat oven to 350 F / 180 C. Butter a 9-inch square baking pan.',
      'In a mixing bowl, stir together flour, granulated sugar, 3 tablespoons of the cocoa, baking powder and salt. With a fork, mix in milk, oil, and vanilla.',
      'Spread the batter evenly in the prepared baking pan.',
      'Combine brown sugar and the remaining 1/4 cup cocoa; sprinkle over the batter.',
      'Slowly pour boiling hot water over the batter and brown sugar-cocoa mixture.',
      'Bake for 40 minutes. Remove to a rack and let stand for 5 minutes.',
      'Spoon into dessert dishes or cut into squares. Serve with ice cream or whipped topping.',
    ],
    isVegetarian: false,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c10',
    ],
    title: 'Blackforest Cheese Cake',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://www.thespruceeats.com/thmb/WRpPBOK-zOZRI8IlmHS--XSODZA=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Copyofcheesecake-docx-21-4-df6176f98d0e493b90b85adeb52237a8.jpeg',
    duration: 35,
    ingredients: [
      '9 ounces chocolate wafer cookies (about 45 two-inch thin wafer cookies)',
      ' 3 tablespoons, plus 1/3 cup granulated sugar (divided)',
      '1 1/4 teaspoons fine sea salt (divided)',
      '1/2 cup unsalted butter (melted)',
      '2 cups semi-sweet chocolate chips',
      '2 cups heavy cream (divided)',
      '24 ounces cream cheese (at room temperature)',
      '1 cup light brown sugar',
      ' 1 tablespoon vanilla extract',
      '4 large eggs (at room temperature)',
      '3 tablespoon all-purpose flour',
      '5 cups sweet cherries (fresh or frozen)',
      '2 teaspoons cornstarch',
      '7 tablespoons Kirsch (divided)',
      '3 tablespoons confectioners’ sugar',
    ],
    steps: [
      'Gather the ingredients and preheat your oven to 350 F.',
      'Grease a 9-inch springform pan with cooking spray or softened butter.',
      'To make the crust, place the wafer cookies, 3 tablespoons of the granulated sugar, and 1/2 teaspoon of the salt in a food processor fitted with the metal blade and process until fine crumbs form. Add the melted butter and process until combined, scraping the bowl periodically with a rubber spatula, if necessary.',
      'Add the melted butter and process until combined, scraping the bowl periodically with a rubber spatula, if necessary.',
      'Transfer the crumbs to the prepared pan and firmly press the crumbs into the bottom and 3/4 of the way up the sides of the pan. Place the crust in the freezer for 30 minutes.',
      'Meanwhile, place the chocolate and 1/2 cup of the heavy cream in a small microwave safe bowl and microwave on high in 30 second bursts, until the chocolate has melted and the mixture is smooth. Set aside to cool to room temperature',
      'Bake the crust for 8 to 10 minutes, rotating at the halfway point until dry and fragrant.',
      'Reduce the speed to low and add the eggs, one at a time, mixing after each addition until incorporated, and scraping down the bowl as needed.',
      'Stir the flour into the cooled chocolate mixture.',
      'Add the chocolate mixture to the stand mixer bowl and mix on low until just combined.',
      'Transfer the filling to the prepared pan and place it on a cookie sheet in the oven. Bake for about 55 to 60 minutes, until the edges are set, but the middle jiggles just a bit.',
      'Turn the oven off, crack the oven door, and leave the cheesecake in the oven to cool for one hour. After one hour, remove cheesecake from oven, and let cool on the counter at room temperature.',
      'For the toppings, place the cherries, 1 /3 cup of the granulated sugar, remaining 1/4 teaspoon of the salt, cornstarch, and 1/4 cup of the Kirsch in a medium saucepan on the stovetop over medium-high heat and cook until the sugar melts and the cherries burst and release their juice, stirring frequently, about 30 minutes. Cool to room temperature.',
      'Place the remaining 1 1/2 cups of the heavy cream, confectioners’ sugar, a few tablespoons of the cherry juice from the compote and the 3 tablespoons of the remaining Kirsch, in the now clean bowl of the stand mixer, fitted with the whisk attachment, and whisk until medium peaks form.',
      'To serve, spread the Kirsh whipped cream over the cooled cheesecake. Serve immediately or chill, tightly covered, in the refrigerator until ready to serve. Serve slices of cheesecake with a generous spoonful or two of the cherry compote.',
    ],
    isVegetarian: false,
  ),
  Meal(
  id: 'm5',
  categories: [
    'c4',
    'c2',
  ],
  title: 'Chana Masala',
  affordability: Affordability.Affordable,
  complexity: Complexity.Challenging,
  imageUrl:
  'https://www.thespruceeats.com/thmb/7A3HS9BeAmwR_mzQZuucjqNT8_s=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/chole-chickpea-curry-1957946-hero-01-a740af2e2b984ddca9e93096d6bc4c89.jpg',
  duration: 65,
  ingredients: [
   '3 large onions (sliced thin, divided)',
   '2 large tomatoes (chopped)',
   '1 tablespoon ginger paste',
   '2 tablespoons garlic paste',
   '2 tablespoons vegetable oil (or canola or sunflower cooking oil)',
   '2 bay leaves',
   '5 to 6 cloves',
   '3 to 4 green cardamoms',
   '5 to 6 peppercorns',
   '1 teaspoon cumin powder',
   '2 teaspoons coriander powder',
   '1/2 teaspoon red chili powder',
   '1/4 teaspoon turmeric powder',
   '2 teaspoons garam masala',
   '2 (15 1/2-ounce) cans of chickpeas',
   'Kosher salt (to taste)',
   'Water (enough to make a gravy)',
   '1-inch piece of ginger (julienned)',
   '2 tablespoons fresh coriander leaves (chopped fine)' ,
  ],
  steps: [
    'Gather the ingredients.',
   'Grind 2 of the sliced onions, the tomatoes, and the ginger and garlic paste together into a smooth paste in a food processor.',
   'Heat the vegetable oil in a deep, thick-bottomed pan on medium heat.',
   'Add the bay leaves, cloves, cardamom, and peppercorns and sauté until slightly darker and mildly fragrant.',
   'Add the remaining sliced onion and fry until light golden in color.',
  ' Add the onion-tomato paste you made earlier and fry till the oil begins to separate from the paste.',
  ' Add the dry, powdered spices—cumin, coriander, red chili, turmeric, and garam masala powders. Sauté, stirring frequently, for 5 more minutes.',
   'Drain the water in the can from the chickpeas and rinse them well under running water.',
   'Now add the chickpeas to the masala you fried up earlier. Stir to mix everything well.',
   'Add salt to taste and enough hot water to make the gravy—about 1 1/2 cups.',
   'Simmer and cook covered for 10 minutes.',
   'Use a flat spoon or potato masher to mash some of the chickpeas coarsely. Stir to mix everything well.',
  'Garnish with juliennes of ginger and finely chopped fresh coriander leaves. A squeeze of lemon and a handful of very finely chopped onion tastes great as a garnish too.',
  'Serve hot and enjoy!',  
],
  isVegetarian: true,
  ),
  Meal(
  id: 'm6',
  categories: [
    'c6',
    'c9',
  ],
  title: 'Punjabi Eggplant',
  affordability: Affordability.Affordable,
  complexity: Complexity.Simple,
  imageUrl:
  'https://www.thespruceeats.com/thmb/5sBOLmT7OFXkpFMXdMIN1etg4wk=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/punjabi-style-eggplant-1957935_22_preview-5b0436818023b900361bfdbd.jpeg',
  duration: 40,
  ingredients: [
    '3 medium-sized eggplants (roughly 1 pound/500 grams)',
    '2 tablespoons vegetable oil',
    '1 teaspoon cumin seeds',
   '2 medium onions (finely chopped)',
   '1 tablespoon garlic paste (or finely chopped garlic)',
   '1-inch piece ginger (finely grated)',
   '2 large tomatoes (finely chopped)',
   '1/2 teaspoon coriander powder',
   '1/2 teaspoon cumin powder',
   '1/2 teaspoon garam masala',
   '2 tablespoons fresh green coriander (finely chopped)',
  'Optional: 2 green chilies',
  ],
  steps: [
   'Gather the ingredients.',
   'Punjabi baingan ka bharta requires that the eggplant is roasted. This can be done in several different ways. The first is to roast it on a gas cooktop by just placing the eggplant straight on the burner and keeping the flame on low setting. Keep turning and cooking until all the skin on the eggplant is charred and the inner flesh looks really soft. A good sign to watch for is that the eggplant seems to cave in on itself.',
   'Or, you can grill the eggplant in your oven broiler or on your barbecue grill. Again, keep turning periodically till all the skin on the eggplant is charred and the inner flesh looks really soft.',
   'The third method is to roast the eggplant in your oven till all the skin on the eggplant is charred and the inner flesh looks really soft.',
   'Once the eggplant is roasted, allow to cool fully and then peel off and discard the charred skin.',
   'Once cool, coarsely mash it and keep aside for later use.',
   'Now set up a pan on medium heat and add the cooking oil. When hot, add the cumin seeds and cook till the spluttering stops.',
   'Add the onions and fry until soft and translucent.',
   'Add the garlic and the ginger and fry for 1 minute.',
   'Add the tomato, optional green chilies, and all the powdered spices, including the garam masala. Stir well and cook for 3 to 5 minutes, stirring often to prevent the spice mix from sticking to the pan. Sprinkle a little water if needed.',
   'Now add the eggplant and mix well. Add the chopped fresh coriander (cilantro) and stir. Cook another minute and turn off the heat.',
   'Serve hot with chapatis or rice and your favorite daal dish.',
],
  isVegetarian: true,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c2',
    ],
    title: 'Pasta',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://i2.wp.com/swatisani.net/kitchen/wp-content/uploads/2015/06/IMG_8878.jpg',
    duration: 35,
    ingredients: [
    '2 Tbsp Butter',
    'Sausages 3-4', 
    'Onions 1 large, chopped finely',
    'Garlic 1 Tsp chopped very finely',
    'Green Peas 1/2 cup',
    'Carrots 1 peeled and chopped',
    'Beans 8-9 chopped',
    'Chicken broth 2 cups',
    'Milk 1 cup',
    'Cream 100 gms',
    'Pepper to taste',
    'Allspice 1 Tsp crushed',
    'Parmesan 3-4 Tbsp grated',
      
    ],
    steps: [
      'Parboil the vegetables with a bit of salt and keep aside',
      'Heat butter in a deep skillet and add onion and garlic. Fry for a few seconds before adding the diced sausages to it. Let it cook till onions are soft and sausages lightly browned. Add the parboiled vegetables and let them get coated with butter completely.',
      'Add milk to the skillet and half the cream (I used Amul Fresh Cream) Let it boil and add the dry pasta along with warm chicken broth. Add some more salt, half the allspice and a pinch of pepper.',
      'Cover and cook until the pasta is al dente. This takes about 12 minutes. Keep checking for the sauce. If you find it going dry, add water or chicken broth',
      'After the pasta is done, check for salt, season with more pepper and allspice and sprinkle the Parmesan.',
      'Mix well and serve.',
    ],
    isVegetarian: true,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c1',
    ],
    title: 'Idli',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://recipes.timesofindia.com/recipes/idli/rs53239358.cms',
    duration: 20,
    ingredients: [
    '2 1/2 cup basmati rice',
    '1 1/2 cup urad dal',
    '1/2 tablespoon fenugreek seeds',
    '1 1/2 teaspoon salt',
    '5 tablespoon sesame oil',
    'water as required',

      
    ],
    steps: [
      'Soak the rice & dal and grind into a paste & combine',
      'Let the batter ferment, then add salt',
      'Transfer the idli batter in the idli stand',
      'Wait for the utensil to cool a bit before scooping the idlis out',

    ],
    isVegetarian: true,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c3',
    ],
    title: 'Poha',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.theloveofspice.com/wp-content/uploads/2019/01/kanda-poha-recipe.jpg',
    duration: 20,
    ingredients: [
    '1.5 cups poha 114 grams, use thick poha',
    '1/4 teaspoon turmeric',
    '1/2 teaspoon + 1/8 teaspoon salt divided, adjust to taste',
    '1/3 cup green peas I used frozen, soaked in warm water for 10 minutes',
    '2 teaspoons oil 10 ml, I used avocado oil',
    '1/2 teaspoon mustard seeds',
    '1.5 tablespoons raw peanuts',
    '1 small red onion chopped',
    '1 green chili chopped',
    '10-12 curry leaves',
    '1/4 teaspoon sugar optional',
    '1 tablespoon chopped cilantro + more to garnish',
    '1/2 lemon juice',

      
    ],
    steps: [
      'To a strainer, add flattened rice (poha). Rinse it under running water until it turns soft.',
      'Add turmeric and 1/2 teaspoon salt to the poha and toss to combine.',
      'Heat oil in a pan on medium heat.Add the mustard seeds and let them pop.',
      'Then add the peanuts and saute for a minute or two.',
      'Then add the chopped onion, green chili and curry leaves. Cook for 2 minutes until the onions soften.',
      'Add the green peas and mix.',
      'Then add in the rinsed poha and toss to combine.',
      'Also add the sugar (if using) and cilantro.And then cover the pan with a lid and turn heat to low for 2 minutes.',
      'Squeeze in some fresh lemon juice. Garnish poha with more cilantro',

    ],
    isVegetarian: true,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c3',
    ],
    title: 'Pakora',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://i.ytimg.com/vi/slo7Y0I2DJQ/maxresdefault.jpg',
    duration: 25,
    ingredients: [
    '3 Onions thinly sliced (approx 1/8 inch)',
    '1 cup Besan or Gram flour',
    '3 tablespoon Rice Flour',
    '2 teaspoon Chilli Powder or Paprika',
    'a pinch Hing or Asafoetida ',
    '¼ teaspoon Ajwain',
    '2 teaspoon Salt',
    '½ tbsp Ginger Garlic paste',
    'a pinch Baking Soda',
    '1 1/2 cups Oil for deep frying',
  
    

      
    ],
    steps: [
      'Thinly Slice Onions.',
      'Add gram flour, rice flour, chilli powder, hing, ajwain, salt, ginger garlic paste and baking soda. Toss the onions in the dry mixture and smash them with your hands. Wait for a few minutes and toss once or twice. The onions will start releasing water and the dry batter will convert into a semi wet mixture.',
      'Add just a tablespoon or so of water if required to create a thick-ish coating around the onions.',
      'Heat oil in a deep pan or kadai over medium flame.',
      'Gently drop lime sized battered onions into the oil.',
      'Fry on a medium flame to ensure the pakodas are cooked from inside. This will take about 3-5 minutes.',
      'Using a skimmer, remove the pakoda and drain the excess oil.',
      'Sprinkle some chaat masala on top and serve hot!',
      

    ],
    isVegetarian: true,
  ),
  Meal(
    id: 'm11',
    categories: [
      'c3',
    ],
    title: 'Mirchi-Bajji',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.theloveofspice.com/wp-content/uploads/2019/01/kanda-poha-recipe.jpg',
    duration: 20,
    ingredients: [
    '4 green chilli (large)',
    '2 cup gram flour / besan',
    '2 tbsp rice flour',
    '¼ tsp ajwain / carom seeds',
    '¼ tsp baking soda',
    '½ tsp salt',
    '¾ cup water',
    '1 tbsp oil',



      
    ],
    steps: [
      'Firstly, take long green chilis and slit at the centre and remove seeds.',
      'Now prepare the bajji batter by taking 2 cup besan and 2 tbsp rice flour in large mixing bowl.',
      'Also add ¼ tsp ajwain, ¼ tsp baking soda and ½ tsp salt and mix well',
      'Add water as requried and prepare a lump free thick batter.'
      'Further pour 1 tbsp of hot oil over the batter and mix well.',
      'Now dip the green chilli and coat it with besan batter completely.',
      'Deep fry in hot oil dropping batter coated chillis slowly',
      'Keeping the flame on medium, flip over and fry all the sides until the bajjis turn crisp and golden brown.',
      

    ],
    isVegetarian: true,
  ),
  Meal(
    id: 'm12',
    categories: [
      'c3',
    ],
    title: 'Upma',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.vegrecipesofindia.com/wp-content/uploads/2009/08/upma-recipe-1-1.jpg',
    duration: 20,
    ingredients: [
   '1 cup rava – finer variety',
'1 cup rava – finer variety',
'1 teaspoon mustard seeds',
'⅓ cup finely chopped onions or 1 medium-sized onion',
'1 teaspoon chopped green chilli or 1 green chilli',
'1 teaspoon finely chopped ginger or 1 inch ginger',
'1 sprig curry leaves or 10 to 12 curry leaves',



      
    ],
    steps: [
      'In a pan, heat ghee or oil. add the mustard seeds.',
      'Now add the finely chopped onions. Saute the onions till they become translucent.',
      'Then add the chopped green chilly, ginger, curry leaves. Sauté for a few seconds. You can also add 1 dried red chilli at this step.',
      'Then add 2.5 cups water, sugar and salt as required.'
      'When the water comes to a rolling boil, lower the flame to its lowest. Then add the rava in 4 to 5 batches with a spoon.',
      'Cover and allow the rava upma to steam for 2 to 3 minutes on a low heat.',
      'Then switch off the flame. Now the rava is cooked and the upma is ready',
 
      

    ],
    isVegetarian: true,
  ),
  Meal(
    id: 'm13',
    categories: [
      'c1',
    ],
    title: 'Appam',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.vegrecipesofindia.com/wp-content/uploads/2014/04/appam-recipe.jpg',
    duration: 20,
    ingredients: [
   '2 cups regular white rice',
'1 cup parboiled rice or boiled rice or idli rice',
'a fistful of poha',
'½ teaspoon dry active yeast',
'1 teaspoon salt or add as required',
'1 to 1.5 cups grated coconut or 1 cup thick coconut milk',
    ],
    steps: [
      'Rinse both the rice varieties together for a couple of times.',
'Soak both the regular rice, parboiled rice in water for 4 to 5 hours.',
'Drain and then add them to the grinder. Also add the grated coconut, cooked rice or poha (aval or flattened rice), dry active yeast, salt and sugar.',
'Add required amount of water and grind all the ingredients to a smooth flowing batter',
'Pour the batter in a large bowl or pan. Cover and keep aside for fermenting for 8 to 12 hours, depending on the temperature conditions.',
'Heat a kadai and Spread a ladle full of the batter',
'Spread a ladle full of the batter',

    ],
    isVegetarian: true,
  ),
  Meal(
    id: 'm14',
    categories: [
      'c2',
    ],
    title: 'Paneer Butter Masala',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.vegrecipesofindia.com/wp-content/uploads/2014/04/appam-recipe.jpg',
    duration: 20,
    ingredients: [
   '½ cup vegetable oil ',
'½ pound paneer, cut into 1/2-inch cubes ',
'2 tablespoons butter ',
'2 onions, finely chopped',
'1 teaspoon garlic paste ',
'1 tablespoon ground cashews',
'1 teaspoon ground red chiles',
'½ teaspoon ground cumin ',
'½ teaspoon garam masala ',
'½ cup milk ',
'½ teaspoon white sugar',
'½ teaspoon salt', 

    ],
    steps: [
      'Heat oil in a large skillet over medium heat; fry paneer in 2 batches until golden, about 5 minutes. Transfer fried paneer to a paper towel-lined plate to drain, retaining vegetable oil in skillet.',
      'Melt butter in the same skillet over medium heat; cook and stir onion until golden brown, about 10 minutes. Add ginger paste and garlic paste. Continue to cook until fragrant, about 1 minute more. Stir cashews, ground red chiles, cumin, coriander, and garam masala into onion mixture. Cook and stir for 1 minute.',
      'Stir tomato sauce, half-and-half, milk, sugar, and salt into spice mixture; simmer until thickened, about 5 minutes. Reduce heat to low. Add fried paneer and simmer until heated through, about 5 minutes more.'
    ],
    isVegetarian: true,
  )
];
